# Generated by Django 5.0.2 on 2024-02-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_item_name_remove_item_user_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.BinaryField(),
        ),
    ]
