# Generated by Django 5.0.2 on 2024-03-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('message_content', models.CharField(default='', max_length=1000)),
                ('recipient_id', models.IntegerField()),
                ('chat_id', models.IntegerField()),
            ],
        ),
    ]
